import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "../shared/providers/QueryProvider";
import { SessionProvider } from "next-auth/react";
import AuthSessionProvider from "@/shared/providers/AuthSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <AuthSessionProvider>
            <div className="mobile-container">
              <main className="main-content">{children}</main>
            </div>
          </AuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
